// 宝可梦风格宠物系统 — 50种宠物，每种3个技能

export type PetElement = 'normal' | 'fire' | 'water' | 'grass' | 'electric' | 'ice' | 'dark' | 'light';

export type PetRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface PetDef {
  id: string;
  name: string;
  element: PetElement;
  rarity: PetRarity;
  description: string;
  icon: string;
  color: number;
  bodyColor: number;
  eyeColor: number;
  stats: PetStats;
  passive: PetPassive;
  active: PetActive;
  active2: PetActive;
  ultimate: PetActive;
  evolution?: {
    toPetId: string;
    requiredLevel: number;
    requiredShards: number;
  };
}

export interface PetStats {
  hpBonus: number;
  attackBonus: number;
  speedBonus: number;
  defenseBonus: number;
}

export interface PetPassive {
  type: string;
  value: number;
  description: string;
}

export interface PetActive {
  name: string;
  cooldown: number;
  duration: number;
  type: string;
  value: number;
  description: string;
}

export interface PetInstance {
  petId: string;
  level: number;
  exp: number;
  friendship: number;
}

export const PET_ELEMENT_COLORS: Record<PetElement, number> = {
  normal: 0x9e9e9e,
  fire: 0xff5722,
  water: 0x2196f3,
  grass: 0x4caf50,
  electric: 0xffeb3b,
  ice: 0x00bcd4,
  dark: 0x616161,
  light: 0xffd700,
};

export const PET_ELEMENT_NAMES: Record<PetElement, string> = {
  normal: '一般',
  fire: '火',
  water: '水',
  grass: '草',
  electric: '电',
  ice: '冰',
  dark: '暗',
  light: '光',
};

export const PETS: PetDef[] = [
  // ═══════════════════════════════════════════════════════════════
  //                        一般系 (6只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_slime',
    name: '小史莱姆',
    element: 'normal',
    rarity: 'common',
    description: '最常见的软体生物，弹性十足',
    icon: '🟢',
    color: 0x9e9e9e,
    bodyColor: 0xbdbdbd,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 0, speedBonus: 0, defenseBonus: 1 },
    passive: { type: 'defense_boost', value: 0.05, description: '5% 概率免疫伤害' },
    active: { name: '弹性冲撞', cooldown: 8000, duration: 0, type: 'bounce', value: 2, description: '弹射冲撞前方敌人' },
    active2: { name: '弹性冲撞·改', cooldown: 6000, duration: 0, type: 'bounce_2', value: 1, description: '弹性冲撞的快速版本' },
    ultimate: { name: '分裂增殖', cooldown: 30000, duration: 0, type: 'split', value: 3, description: '分裂出3个小史莱姆辅助攻击' },
  },
  {
    id: 'pet_bunny',
    name: '跳跳兔',
    element: 'normal',
    rarity: 'common',
    description: '蹦蹦跳跳的可爱兔子，跳跃力惊人',
    icon: '🐰',
    color: 0xf5f5f5,
    bodyColor: 0xeeeeee,
    eyeColor: 0xe91e63,
    stats: { hpBonus: 0, attackBonus: 0, speedBonus: 3, defenseBonus: 0 },
    passive: { type: 'jump_boost', value: 0.10, description: '跳跃高度 +10%' },
    active: { name: '兔蹬鹰', cooldown: 10000, duration: 0, type: 'rabbit_kick', value: 3, description: '高高跃起后猛踹，伤害 3 点' },
    active2: { name: '兔蹬鹰·改', cooldown: 7000, duration: 0, type: 'rabbit_kick_2', value: 2, description: '兔蹬鹰的快速版本' },
    ultimate: { name: '月面飞跃', cooldown: 35000, duration: 5000, type: 'moon_jump', value: 1, description: '5秒内跳跃高度翻倍且可二段跳' },
  },
  {
    id: 'pet_rock',
    name: '岩石仔',
    element: 'normal',
    rarity: 'uncommon',
    description: '由岩石凝聚而成的小精灵，坚不可摧',
    icon: '🪨',
    color: 0x795548,
    bodyColor: 0x8d6e63,
    eyeColor: 0xffeb3b,
    stats: { hpBonus: 2, attackBonus: 1, speedBonus: -2, defenseBonus: 4 },
    passive: { type: 'defense_boost', value: 0.12, description: '12% 概率免疫伤害' },
    active: { name: '岩石封锁', cooldown: 12000, duration: 3000, type: 'rock_tomb', value: 2, description: '召唤岩柱封锁路径，持续 3 秒' },
    active2: { name: '岩石封锁·改', cooldown: 9000, duration: 3000, type: 'rock_tomb_2', value: 1, description: '岩石封锁的快速版本' },
    ultimate: { name: '山崩地裂', cooldown: 40000, duration: 0, type: 'landslide', value: 6, description: '巨岩从天而降，全屏伤害 6 点' },
  },
  {
    id: 'pet_fox',
    name: '灵狐',
    element: 'normal',
    rarity: 'uncommon',
    description: '聪明伶俐的狐狸，善于迷惑敌人',
    icon: '🦊',
    color: 0xff9800,
    bodyColor: 0xffa726,
    eyeColor: 0x4caf50,
    stats: { hpBonus: 0, attackBonus: 2, speedBonus: 3, defenseBonus: 0 },
    passive: { type: 'dodge', value: 0.08, description: '8% 概率闪避攻击' },
    active: { name: '幻影分身', cooldown: 14000, duration: 4000, type: 'illusion', value: 1, description: '4秒内敌人无法锁定你' },
    active2: { name: '幻影分身·改', cooldown: 11000, duration: 4000, type: 'illusion_2', value: 1, description: '幻影分身的快速版本' },
    ultimate: { name: '狐火燎原', cooldown: 35000, duration: 0, type: 'foxfire', value: 5, description: '释放狐火追踪最近 5 个敌人' },
  },
  {
    id: 'pet_eevee',
    name: '伊布',
    element: 'normal',
    rarity: 'rare',
    description: '不稳定的遗传因子，进化方向多样',
    icon: '🦊',
    color: 0x8d6e63,
    bodyColor: 0xa1887f,
    eyeColor: 0x4a148c,
    stats: { hpBonus: 1, attackBonus: 1, speedBonus: 1, defenseBonus: 1 },
    passive: { type: 'all_boost', value: 0.02, description: '全属性 +2%' },
    active: { name: '珍藏', cooldown: 18000, duration: 0, type: 'last_resort', value: 4, description: '积蓄力量释放，伤害 4 点' },
    active2: { name: '珍藏·改', cooldown: 15000, duration: 0, type: 'last_resort_2', value: 3, description: '珍藏的快速版本' },
    ultimate: { name: '进化之力', cooldown: 45000, duration: 8000, type: 'evolve', value: 1, description: '8秒内全属性提升 50%' },
  },
  {
    id: 'pet_snorlax',
    name: '卡比兽',
    element: 'normal',
    rarity: 'epic',
    description: '每天睡 20 小时，醒来就是吃',
    icon: '🐻',
    color: 0x37474f,
    bodyColor: 0x546e7a,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 5, attackBonus: 3, speedBonus: -3, defenseBonus: 4 },
    passive: { type: 'regen', value: 1, description: '每 15 秒恢复 1 条生命' },
    active: { name: '睡觉', cooldown: 20000, duration: 3000, type: 'rest', value: 3, description: '回复 3 条生命，期间无敌但无法移动' },
    active2: { name: '睡觉·改', cooldown: 17000, duration: 3000, type: 'rest_2', value: 2, description: '睡觉的快速版本' },
    ultimate: { name: '终极冲击', cooldown: 50000, duration: 0, type: 'giga_impact', value: 10, description: '全力冲撞，伤害 10 点' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        火系 (7只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_candle',
    name: '烛火灵',
    element: 'fire',
    rarity: 'common',
    description: '微弱的烛火精灵，火焰虽小却温暖',
    icon: '🕯️',
    color: 0xff9800,
    bodyColor: 0xffa726,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 0, attackBonus: 2, speedBonus: 1, defenseBonus: 0 },
    passive: { type: 'fire_touch', value: 1, description: '接触敌人造成 1 点灼烧' },
    active: { name: '烛光闪烁', cooldown: 8000, duration: 0, type: 'flash', value: 2, description: '闪光致盲附近敌人 2 秒' },
    active2: { name: '烛光闪烁·改', cooldown: 6000, duration: 0, type: 'flash_2', value: 1, description: '烛光闪烁的快速版本' },
    ultimate: { name: '引燃', cooldown: 30000, duration: 0, type: 'ignite', value: 4, description: '点燃周围所有敌人，持续伤害 4 点' },
  },
  {
    id: 'pet_firedrake',
    name: '火蜥蜴',
    element: 'fire',
    rarity: 'uncommon',
    description: '在岩浆中孵化的小型火龙',
    icon: '🦎',
    color: 0xff5722,
    bodyColor: 0xff7043,
    eyeColor: 0xffeb3b,
    stats: { hpBonus: 0, attackBonus: 3, speedBonus: 1, defenseBonus: 0 },
    passive: { type: 'attack_boost', value: 3, description: '踩踏伤害 +3' },
    active: { name: '火花溅射', cooldown: 10000, duration: 0, type: 'ember', value: 3, description: '发射火花弹，命中后溅射伤害' },
    active2: { name: '火花溅射·改', cooldown: 7000, duration: 0, type: 'ember_2', value: 2, description: '火花溅射的快速版本' },
    ultimate: { name: '火焰漩涡', cooldown: 35000, duration: 4000, type: 'fire_spin', value: 2, description: '火焰漩涡包裹敌人，4秒持续伤害' },
    evolution: { toPetId: 'pet_charmander', requiredLevel: 4, requiredShards: 20 },
  },
  {
    id: 'pet_charmander',
    name: '小火龙',
    element: 'fire',
    rarity: 'uncommon',
    description: '尾巴上的火焰代表生命力，越强越旺',
    icon: '🔥',
    color: 0xff5722,
    bodyColor: 0xff7043,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 0, attackBonus: 4, speedBonus: 1, defenseBonus: 0 },
    passive: { type: 'attack_boost', value: 4, description: '踩踏伤害 +4' },
    active: { name: '喷射火焰', cooldown: 12000, duration: 3000, type: 'fire_trail', value: 2, description: '身后留下火焰路径，持续 3 秒' },
    active2: { name: '喷射火焰·改', cooldown: 9000, duration: 3000, type: 'fire_trail_2', value: 1, description: '喷射火焰的快速版本' },
    ultimate: { name: '大字爆', cooldown: 35000, duration: 0, type: 'fire_explosion', value: 7, description: '前方大范围火焰爆炸，伤害 7' },
    evolution: { toPetId: 'pet_charmeleon', requiredLevel: 6, requiredShards: 40 },
  },
  {
    id: 'pet_charmeleon',
    name: '火恐龙',
    element: 'fire',
    rarity: 'rare',
    description: '性格粗暴，火焰更加猛烈',
    icon: '🔥',
    color: 0xff3d00,
    bodyColor: 0xe64a19,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 6, speedBonus: 2, defenseBonus: 0 },
    passive: { type: 'attack_boost', value: 6, description: '踩踏伤害 +6' },
    active: { name: '火焰牙', cooldown: 10000, duration: 0, type: 'fire_fang', value: 5, description: '火焰撕咬，有概率灼烧敌人' },
    active2: { name: '火焰牙·改', cooldown: 7000, duration: 0, type: 'fire_fang_2', value: 4, description: '火焰牙的快速版本' },
    ultimate: { name: '炼狱', cooldown: 40000, duration: 0, type: 'inferno', value: 8, description: '释放地狱之火，全屏灼烧伤害 8' },
    evolution: { toPetId: 'pet_charizard', requiredLevel: 8, requiredShards: 60 },
  },
  {
    id: 'pet_charizard',
    name: '喷火龙',
    element: 'fire',
    rarity: 'epic',
    description: '传说中的火龙，翅膀可掀起飓风',
    icon: '🐉',
    color: 0xff3d00,
    bodyColor: 0xe64a19,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 2, attackBonus: 8, speedBonus: 3, defenseBonus: 1 },
    passive: { type: 'attack_boost', value: 8, description: '踩踏伤害 +8' },
    active: { name: '喷射火焰', cooldown: 12000, duration: 4000, type: 'flamethrower', value: 4, description: '4秒持续喷射火焰' },
    active2: { name: '喷射火焰·改', cooldown: 9000, duration: 4000, type: 'flamethrower_2', value: 3, description: '喷射火焰的快速版本' },
    ultimate: { name: '爆炸烈焰', cooldown: 45000, duration: 0, type: 'blast_burn', value: 12, description: '释放最强火焰技，全屏爆炸伤害 12' },
  },
  {
    id: 'pet_flareon',
    name: '火伊布',
    element: 'fire',
    rarity: 'epic',
    description: '体内火焰袋可产生 1700° 高温',
    icon: '🦊',
    color: 0xff3d00,
    bodyColor: 0xe64a19,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 7, speedBonus: 1, defenseBonus: 2 },
    passive: { type: 'attack_boost', value: 7, description: '踩踏伤害 +7' },
    active: { name: '闪焰冲锋', cooldown: 12000, duration: 2000, type: 'flare_blitz', value: 4, description: '火焰冲锋，2 秒内接触敌人自动消灭' },
    active2: { name: '闪焰冲锋·改', cooldown: 9000, duration: 2000, type: 'flare_blitz_2', value: 3, description: '闪焰冲锋的快速版本' },
    ultimate: { name: '过热', cooldown: 40000, duration: 0, type: 'overheat', value: 10, description: '释放全部热能，伤害 10 点但自身减速 3 秒' },
  },
  {
    id: 'pet_moltres',
    name: '火焰鸟',
    element: 'fire',
    rarity: 'legendary',
    description: '传说中的三圣鸟之一，浴火重生',
    icon: '🦅',
    color: 0xff6d00,
    bodyColor: 0xff9100,
    eyeColor: 0xc62828,
    stats: { hpBonus: 3, attackBonus: 7, speedBonus: 5, defenseBonus: 2 },
    passive: { type: 'fire_aura', value: 1, description: '周围敌人持续受到 1 点灼烧' },
    active: { name: '神圣之火', cooldown: 15000, duration: 0, type: 'sacred_fire', value: 6, description: '圣火净化，全屏伤害 6 点' },
    active2: { name: '神圣之火·改', cooldown: 12000, duration: 0, type: 'sacred_fire_2', value: 5, description: '神圣之火的快速版本' },
    ultimate: { name: '浴火重生', cooldown: 60000, duration: 0, type: 'rebirth', value: 1, description: '死亡时自动复活并回复全部生命（每关一次）' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        水系 (7只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_bubble',
    name: '泡泡鱼',
    element: 'water',
    rarity: 'common',
    description: '透明的水泡生物，在水中自由漂浮',
    icon: '🫧',
    color: 0x42a5f5,
    bodyColor: 0x90caf9,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 0, speedBonus: 0, defenseBonus: 2 },
    passive: { type: 'defense_boost', value: 0.06, description: '6% 概率免疫伤害' },
    active: { name: '水泡弹', cooldown: 8000, duration: 0, type: 'bubble_beam', value: 2, description: '发射水泡弹，命中后困住敌人' },
    active2: { name: '水泡弹·改', cooldown: 6000, duration: 0, type: 'bubble_beam_2', value: 1, description: '水泡弹的快速版本' },
    ultimate: { name: '潮汐涌动', cooldown: 30000, duration: 0, type: 'tide', value: 4, description: '潮水涌来，推开并伤害所有地面敌人' },
  },
  {
    id: 'pet_crab',
    name: '钳钳蟹',
    element: 'water',
    rarity: 'common',
    description: '坚硬的蟹壳是最好的铠甲',
    icon: '🦀',
    color: 0xe53935,
    bodyColor: 0xef5350,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 1, speedBonus: -1, defenseBonus: 3 },
    passive: { type: 'defense_boost', value: 0.08, description: '8% 概率免疫伤害' },
    active: { name: '蟹钳夹击', cooldown: 10000, duration: 0, type: 'crab_hammer', value: 3, description: '巨钳猛击，伤害 3 点' },
    active2: { name: '蟹钳夹击·改', cooldown: 7000, duration: 0, type: 'crab_hammer_2', value: 2, description: '蟹钳夹击的快速版本' },
    ultimate: { name: '坚壳冲锋', cooldown: 32000, duration: 3000, type: 'shell_charge', value: 1, description: '3秒内防御翻倍且冲锋无敌' },
  },
  {
    id: 'pet_squirtle',
    name: '杰尼龟',
    element: 'water',
    rarity: 'uncommon',
    description: '壳可抵挡攻击，水枪精准',
    icon: '🐢',
    color: 0x2196f3,
    bodyColor: 0x42a5f5,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 0, speedBonus: 0, defenseBonus: 4 },
    passive: { type: 'defense_boost', value: 0.10, description: '10% 概率免疫伤害' },
    active: { name: '水枪', cooldown: 10000, duration: 2000, type: 'water_gun', value: 2, description: '高压水枪，推开并伤害前方敌人' },
    active2: { name: '水枪·改', cooldown: 7000, duration: 2000, type: 'water_gun_2', value: 1, description: '水枪的快速版本' },
    ultimate: { name: '水之护盾', cooldown: 38000, duration: 5000, type: 'water_shield', value: 1, description: '水之护盾包裹，5 秒内免疫伤害' },
    evolution: { toPetId: 'pet_wartortle', requiredLevel: 5, requiredShards: 30 },
  },
  {
    id: 'pet_wartortle',
    name: '卡咪龟',
    element: 'water',
    rarity: 'rare',
    description: '尾巴蓬松，长寿象征',
    icon: '🐢',
    color: 0x1565c0,
    bodyColor: 0x1e88e5,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 2, attackBonus: 1, speedBonus: 0, defenseBonus: 6 },
    passive: { type: 'defense_boost', value: 0.15, description: '15% 概率免疫伤害' },
    active: { name: '水炮', cooldown: 12000, duration: 0, type: 'hydro_pump', value: 5, description: '高压水炮，伤害 5 点' },
    active2: { name: '水炮·改', cooldown: 9000, duration: 0, type: 'hydro_pump_2', value: 4, description: '水炮的快速版本' },
    ultimate: { name: '急冻光线', cooldown: 40000, duration: 4000, type: 'ice_beam', value: 3, description: '冻结前方所有敌人 4 秒' },
    evolution: { toPetId: 'pet_blastoise', requiredLevel: 8, requiredShards: 60 },
  },
  {
    id: 'pet_blastoise',
    name: '水箭龟',
    element: 'water',
    rarity: 'epic',
    description: '背上的水炮可发射高压水流',
    icon: '🐢',
    color: 0x0d47a1,
    bodyColor: 0x1565c0,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 3, attackBonus: 3, speedBonus: 0, defenseBonus: 8 },
    passive: { type: 'defense_boost', value: 0.18, description: '18% 概率免疫伤害' },
    active: { name: '双炮水击', cooldown: 12000, duration: 0, type: 'dual_cannon', value: 7, description: '双管水炮齐射，伤害 7 点' },
    active2: { name: '双炮水击·改', cooldown: 9000, duration: 0, type: 'dual_cannon_2', value: 6, description: '双炮水击的快速版本' },
    ultimate: { name: '高压水炮阵', cooldown: 45000, duration: 6000, type: 'cannon阵列', value: 3, description: '6秒内持续发射水炮，每秒伤害 3' },
  },
  {
    id: 'pet_vaporeon',
    name: '水伊布',
    element: 'water',
    rarity: 'epic',
    description: '细胞结构与水分子相似，可溶于水中',
    icon: '🐬',
    color: 0x00bcd4,
    bodyColor: 0x26c6da,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 3, attackBonus: 2, speedBonus: 2, defenseBonus: 5 },
    passive: { type: 'water_body', value: 0.20, description: '20% 概率免疫伤害 + 水中无敌' },
    active: { name: '水之波动', cooldown: 15000, duration: 5000, type: 'water_pulse', value: 3, description: '水波护体，5 秒内持续伤害靠近的敌人' },
    active2: { name: '水之波动·改', cooldown: 12000, duration: 5000, type: 'water_pulse_2', value: 2, description: '水之波动的快速版本' },
    ultimate: { name: '高压水泵', cooldown: 42000, duration: 0, type: 'hydro_cannon', value: 9, description: '释放最强水技，贯穿全屏伤害 9' },
  },
  {
    id: 'pet_articuno',
    name: '急冻鸟',
    element: 'water',
    rarity: 'legendary',
    description: '传说中的冰鸟，所到之处霜雪纷飞',
    icon: '🐦',
    color: 0x4fc3f7,
    bodyColor: 0x81d4fa,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 3, attackBonus: 5, speedBonus: 5, defenseBonus: 4 },
    passive: { type: 'frost_aura', value: 1, description: '周围敌人移动速度降低 20%' },
    active: { name: '暴风雪', cooldown: 15000, duration: 4000, type: 'blizzard', value: 4, description: '暴风雪席卷，4秒内全屏持续伤害' },
    active2: { name: '暴风雪·改', cooldown: 12000, duration: 4000, type: 'blizzard_2', value: 3, description: '暴风雪的快速版本' },
    ultimate: { name: '绝对零度', cooldown: 60000, duration: 0, type: 'sheer_cold', value: 1, description: '有概率一击消灭任何敌人' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        草系 (6只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_seed',
    name: '种子精灵',
    element: 'grass',
    rarity: 'common',
    description: '随风飘散的种子，落地生根',
    icon: '🌱',
    color: 0x66bb6a,
    bodyColor: 0x81c784,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 1, speedBonus: 0, defenseBonus: 1 },
    passive: { type: 'regen', value: 1, description: '每 25 秒恢复 1 条生命' },
    active: { name: '种子机关枪', cooldown: 10000, duration: 0, type: 'bullet_seed', value: 1, description: '连续发射 5 颗种子，每颗伤害 1' },
    active2: { name: '种子机关枪·改', cooldown: 7000, duration: 0, type: 'bullet_seed_2', value: 1, description: '种子机关枪的快速版本' },
    ultimate: { name: '疯狂生长', cooldown: 30000, duration: 5000, type: 'overgrow', value: 1, description: '5秒内攻击力翻倍，踩踏伤害翻倍' },
  },
  {
    id: 'pet_mushroom',
    name: '蘑菇仔',
    element: 'grass',
    rarity: 'common',
    description: '释放孢子的可爱蘑菇',
    icon: '🍄',
    color: 0x8d6e63,
    bodyColor: 0xa1887f,
    eyeColor: 0x4caf50,
    stats: { hpBonus: 2, attackBonus: 1, speedBonus: -1, defenseBonus: 1 },
    passive: { type: 'spore_cloud', value: 1, description: '被攻击时释放孢子，减速附近敌人' },
    active: { name: '毒孢子', cooldown: 12000, duration: 5000, type: 'toxic', value: 1, description: '释放毒孢子，5秒内敌人持续掉血' },
    active2: { name: '毒孢子·改', cooldown: 9000, duration: 5000, type: 'toxic_2', value: 1, description: '毒孢子的快速版本' },
    ultimate: { name: '蘑菇炸弹', cooldown: 35000, duration: 0, type: 'spore_bomb', value: 6, description: '巨型蘑菇爆炸，范围伤害 6 点' },
  },
  {
    id: 'pet_bulbasaur',
    name: '妙蛙种子',
    element: 'grass',
    rarity: 'uncommon',
    description: '背上的种子会随阳光成长',
    icon: '🌿',
    color: 0x4caf50,
    bodyColor: 0x66bb6a,
    eyeColor: 0xc62828,
    stats: { hpBonus: 2, attackBonus: 1, speedBonus: 0, defenseBonus: 2 },
    passive: { type: 'regen', value: 1, description: '每 20 秒恢复 1 条生命' },
    active: { name: '藤鞭', cooldown: 10000, duration: 0, type: 'vine_whip', value: 3, description: '藤鞭横扫，伤害并眩晕前方敌人' },
    active2: { name: '藤鞭·改', cooldown: 7000, duration: 0, type: 'vine_whip_2', value: 2, description: '藤鞭的快速版本' },
    ultimate: { name: '飞叶快刀', cooldown: 35000, duration: 0, type: 'razor_leaf', value: 5, description: '飞叶旋转切割，全屏伤害 5 点' },
    evolution: { toPetId: 'pet_ivysaur', requiredLevel: 5, requiredShards: 30 },
  },
  {
    id: 'pet_ivysaur',
    name: '妙蛙草',
    element: 'grass',
    rarity: 'rare',
    description: '花苞散发催眠粉',
    icon: '🌿',
    color: 0x2e7d32,
    bodyColor: 0x388e3c,
    eyeColor: 0xc62828,
    stats: { hpBonus: 3, attackBonus: 3, speedBonus: 0, defenseBonus: 3 },
    passive: { type: 'regen', value: 1, description: '每 15 秒恢复 1 条生命' },
    active: { name: '飞叶风暴', cooldown: 12000, duration: 3000, type: 'leaf_storm', value: 3, description: '飞叶旋转，3 秒内持续伤害周围敌人' },
    active2: { name: '飞叶风暴·改', cooldown: 9000, duration: 3000, type: 'leaf_storm_2', value: 2, description: '飞叶风暴的快速版本' },
    ultimate: { name: '催眠粉', cooldown: 38000, duration: 4000, type: 'sleep_powder', value: 1, description: '催眠附近所有敌人 4 秒' },
    evolution: { toPetId: 'pet_venusaur', requiredLevel: 8, requiredShards: 60 },
  },
  {
    id: 'pet_venusaur',
    name: '妙蛙花',
    element: 'grass',
    rarity: 'epic',
    description: '背上的花朵散发浓郁芳香',
    icon: '🌸',
    color: 0x2e7d32,
    bodyColor: 0x388e3c,
    eyeColor: 0xc62828,
    stats: { hpBonus: 4, attackBonus: 5, speedBonus: 0, defenseBonus: 4 },
    passive: { type: 'regen', value: 1, description: '每 10 秒恢复 1 条生命' },
    active: { name: '日光束', cooldown: 15000, duration: 0, type: 'solar_beam', value: 7, description: '积蓄阳光后发射光束，伤害 7 点' },
    active2: { name: '日光束·改', cooldown: 12000, duration: 0, type: 'solar_beam_2', value: 6, description: '日光束的快速版本' },
    ultimate: { name: '花之舞', cooldown: 45000, duration: 6000, type: 'petal_dance', value: 3, description: '花瓣飞舞，6秒内持续伤害并回复生命' },
  },
  {
    id: 'pet_celebi',
    name: '时拉比',
    element: 'grass',
    rarity: 'legendary',
    description: '穿越时空的森林之神',
    icon: '🧚',
    color: 0x81c784,
    bodyColor: 0xa5d6a7,
    eyeColor: 0x4caf50,
    stats: { hpBonus: 3, attackBonus: 4, speedBonus: 5, defenseBonus: 3 },
    passive: { type: 'time_rewind', value: 1, description: '死亡时有 20% 概率回溯到 5 秒前状态' },
    active: { name: '治愈之愿', cooldown: 18000, duration: 0, type: 'healing_wish', value: 5, description: '回复 5 条生命' },
    active2: { name: '治愈之愿·改', cooldown: 15000, duration: 0, type: 'healing_wish_2', value: 4, description: '治愈之愿的快速版本' },
    ultimate: { name: '时光回溯', cooldown: 60000, duration: 0, type: 'time_travel', value: 1, description: '回溯到本关开始时的状态' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        电系 (6只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_spark',
    name: '电火花',
    element: 'electric',
    rarity: 'common',
    description: '微弱的电弧精灵，在雷雨天出没',
    icon: '⚡',
    color: 0xffee58,
    bodyColor: 0xfff176,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 0, attackBonus: 1, speedBonus: 2, defenseBonus: 0 },
    passive: { type: 'speed_boost', value: 0.05, description: '移动速度 +5%' },
    active: { name: '电击', cooldown: 8000, duration: 0, type: 'thundershock', value: 2, description: '释放电击，伤害 2 点并麻痹敌人' },
    active2: { name: '电击·改', cooldown: 6000, duration: 0, type: 'thundershock_2', value: 1, description: '电击的快速版本' },
    ultimate: { name: '电磁风暴', cooldown: 30000, duration: 3000, type: 'storm', value: 2, description: '电磁风暴，3秒内持续电击周围敌人' },
  },
  {
    id: 'pet_pikachu',
    name: '皮卡丘',
    element: 'electric',
    rarity: 'uncommon',
    description: '黄色电气老鼠，尾巴可释放强力电击',
    icon: '⚡',
    color: 0xffeb3b,
    bodyColor: 0xffee58,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 0, attackBonus: 2, speedBonus: 4, defenseBonus: 0 },
    passive: { type: 'speed_boost', value: 0.08, description: '移动速度 +8%' },
    active: { name: '十万伏特', cooldown: 12000, duration: 0, type: 'thunderbolt', value: 4, description: '释放强力电击，全屏伤害 4 点' },
    active2: { name: '十万伏特·改', cooldown: 9000, duration: 0, type: 'thunderbolt_2', value: 3, description: '十万伏特的快速版本' },
    ultimate: { name: '雷神降临', cooldown: 38000, duration: 0, type: 'thunder', value: 8, description: '召唤天雷劈下，全屏伤害 8 点' },
    evolution: { toPetId: 'pet_raichu', requiredLevel: 6, requiredShards: 40 },
  },
  {
    id: 'pet_raichu',
    name: '雷丘',
    element: 'electric',
    rarity: 'rare',
    description: '进化后的电气鼠，电力更加强劲',
    icon: '⚡',
    color: 0xff8f00,
    bodyColor: 0xffa000,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 4, speedBonus: 6, defenseBonus: 0 },
    passive: { type: 'speed_boost', value: 0.12, description: '移动速度 +12%' },
    active: { name: '疯狂伏特', cooldown: 12000, duration: 2000, type: 'volt_tackle', value: 5, description: '电气冲锋，2秒内无敌并伤害接触的敌人' },
    active2: { name: '疯狂伏特·改', cooldown: 9000, duration: 2000, type: 'volt_tackle_2', value: 4, description: '疯狂伏特的快速版本' },
    ultimate: { name: '雷电风暴', cooldown: 42000, duration: 5000, type: 'thunder_storm', value: 3, description: '5秒内持续召唤落雷攻击敌人' },
  },
  {
    id: 'pet_magnemite',
    name: '小磁怪',
    element: 'electric',
    rarity: 'uncommon',
    description: '悬浮的磁铁精灵，可吸收金属碎片',
    icon: '🧲',
    color: 0x90a4ae,
    bodyColor: 0xb0bec5,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 0, attackBonus: 3, speedBonus: 0, defenseBonus: 3 },
    passive: { type: 'magnet_pull', value: 1, description: '自动吸引附近的金币和碎片' },
    active: { name: '磁力炸弹', cooldown: 12000, duration: 0, type: 'magnet_bomb', value: 4, description: '发射磁力炸弹，必中且伤害 4' },
    active2: { name: '磁力炸弹·改', cooldown: 9000, duration: 0, type: 'magnet_bomb_2', value: 3, description: '磁力炸弹的快速版本' },
    ultimate: { name: '电磁炮', cooldown: 40000, duration: 0, type: 'zap_cannon', value: 9, description: '发射电磁炮，贯穿全屏伤害 9' },
    evolution: { toPetId: 'pet_magneton', requiredLevel: 5, requiredShards: 30 },
  },
  {
    id: 'pet_jolteon',
    name: '雷伊布',
    element: 'electric',
    rarity: 'epic',
    description: '体内蓄满高压电，毛发如针',
    icon: '⚡',
    color: 0xffd600,
    bodyColor: 0xffee58,
    eyeColor: 0xc62828,
    stats: { hpBonus: 0, attackBonus: 5, speedBonus: 8, defenseBonus: 0 },
    passive: { type: 'speed_boost', value: 0.15, description: '移动速度 +15%' },
    active: { name: '雷光闪', cooldown: 10000, duration: 0, type: 'thunder_flash', value: 5, description: '闪电劈下，全屏伤害 5 点' },
    active2: { name: '雷光闪·改', cooldown: 7000, duration: 0, type: 'thunder_flash_2', value: 4, description: '雷光闪的快速版本' },
    ultimate: { name: '电磁加速', cooldown: 42000, duration: 8000, type: 'agility', value: 1, description: '8秒内速度翻倍，闪避率 30%' },
  },
  {
    id: 'pet_zapdos',
    name: '闪电鸟',
    element: 'electric',
    rarity: 'legendary',
    description: '传说中的雷鸟，掌控雷电之力',
    icon: '🐦',
    color: 0xffd600,
    bodyColor: 0xffee58,
    eyeColor: 0xc62828,
    stats: { hpBonus: 2, attackBonus: 6, speedBonus: 7, defenseBonus: 2 },
    passive: { type: 'lightning_rod', value: 1, description: '吸引并免疫所有电系攻击' },
    active: { name: '雷电闪光', cooldown: 14000, duration: 0, type: 'thunder_flash_2', value: 7, description: '闪光雷击，全屏伤害 7 点' },
    active2: { name: '雷电闪光·改', cooldown: 11000, duration: 0, type: 'thunder_flash_2_2', value: 6, description: '雷电闪光的快速版本' },
    ultimate: { name: '万雷天降', cooldown: 60000, duration: 8000, type: 'thousand_thunders', value: 2, description: '8秒内持续降下天雷，每秒伤害 2' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        冰系 (6只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_snowman',
    name: '雪球精灵',
    element: 'ice',
    rarity: 'common',
    description: '由纯净的雪凝聚而成的小精灵',
    icon: '⛄',
    color: 0xe3f2fd,
    bodyColor: 0xffffff,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 0, speedBonus: 0, defenseBonus: 2 },
    passive: { type: 'frost_armor', value: 0.05, description: '受到攻击时 5% 概率冻结攻击者' },
    active: { name: '雪球投掷', cooldown: 8000, duration: 0, type: 'snowball', value: 2, description: '投掷雪球，命中后减速敌人' },
    active2: { name: '雪球投掷·改', cooldown: 6000, duration: 0, type: 'snowball_2', value: 1, description: '雪球投掷的快速版本' },
    ultimate: { name: '暴风雪', cooldown: 30000, duration: 4000, type: 'snowstorm', value: 2, description: '4秒内暴风雪持续伤害并减速敌人' },
  },
  {
    id: 'pet_seal',
    name: '海豹球',
    element: 'ice',
    rarity: 'common',
    description: '圆滚滚的冰系海豹，喜欢在冰面上打滚',
    icon: '🦭',
    color: 0x90caf9,
    bodyColor: 0xbbdefb,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 2, attackBonus: 1, speedBonus: -1, defenseBonus: 2 },
    passive: { type: 'ice_slide', value: 1, description: '在冰面上移动速度不减' },
    active: { name: '冰球滚动', cooldown: 10000, duration: 2000, type: 'ice_ball', value: 3, description: '变成冰球滚动，2秒内伤害接触的敌人' },
    active2: { name: '冰球滚动·改', cooldown: 7000, duration: 2000, type: 'ice_ball_2', value: 2, description: '冰球滚动的快速版本' },
    ultimate: { name: '绝对零度', cooldown: 35000, duration: 0, type: 'sheer_cold_2', value: 5, description: '释放极寒之气，全屏伤害 5 点' },
  },
  {
    id: 'pet_cubchoo',
    name: '冻冻熊',
    element: 'ice',
    rarity: 'uncommon',
    description: '总是流鼻涕的小熊，鼻涕是强力粘液',
    icon: '🐻‍❄️',
    color: 0x90caf9,
    bodyColor: 0xe3f2fd,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 2, attackBonus: 2, speedBonus: 0, defenseBonus: 2 },
    passive: { type: 'ice_touch', value: 1, description: '踩踏敌人时有 15% 概率冻结 2 秒' },
    active: { name: '冰冻之风', cooldown: 12000, duration: 3000, type: 'icy_wind', value: 3, description: '释放寒风，3秒内减速所有敌人 50%' },
    active2: { name: '冰冻之风·改', cooldown: 9000, duration: 3000, type: 'icy_wind_2', value: 2, description: '冰冻之风的快速版本' },
    ultimate: { name: '冰晶爆发', cooldown: 38000, duration: 0, type: 'ice_crash', value: 6, description: '冰晶爆炸，范围伤害 6 点并冻结 3 秒' },
  },
  {
    id: 'pet_glalie',
    name: '冰鬼护',
    element: 'ice',
    rarity: 'rare',
    description: '可以冻结周围空气的冰系精灵',
    icon: '👹',
    color: 0x78909c,
    bodyColor: 0x90a4ae,
    eyeColor: 0xc62828,
    stats: { hpBonus: 2, attackBonus: 3, speedBonus: 1, defenseBonus: 3 },
    passive: { type: 'frost_aura', value: 0.10, description: '附近敌人移动速度降低 10%' },
    active: { name: '冰冻光束', cooldown: 12000, duration: 3000, type: 'ice_beam', value: 4, description: '发射冰冻光束，冻结敌人 3 秒' },
    active2: { name: '冰冻光束·改', cooldown: 9000, duration: 3000, type: 'ice_beam_2', value: 3, description: '冰冻光束的快速版本' },
    ultimate: { name: '冰封世界', cooldown: 42000, duration: 5000, type: 'frost_world', value: 2, description: '5秒内全屏敌人持续被冻结和伤害' },
  },
  {
    id: 'pet_frosmoth',
    name: '雪绒蛾',
    element: 'ice',
    rarity: 'epic',
    description: '翅膀撒下冰晶鳞粉，美丽而致命',
    icon: '🦋',
    color: 0xb3e5fc,
    bodyColor: 0xe1f5fe,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 4, speedBonus: 3, defenseBonus: 3 },
    passive: { type: 'frost_dust', value: 1, description: '被攻击时释放冰粉，减速攻击者 30%' },
    active: { name: '极光束', cooldown: 14000, duration: 0, type: 'aurora_beam', value: 5, description: '发射极光束，伤害 5 并降低敌人攻击力' },
    active2: { name: '极光束·改', cooldown: 11000, duration: 0, type: 'aurora_beam_2', value: 4, description: '极光束的快速版本' },
    ultimate: { name: '冰晶之舞', cooldown: 42000, duration: 6000, type: 'ice_dance', value: 3, description: '6秒内冰晶环绕，持续伤害并冻结附近敌人' },
  },
  {
    id: 'pet_articuno2',
    name: '冰晶凤凰',
    element: 'ice',
    rarity: 'legendary',
    description: '传说中的冰凤凰，涅槃于寒冰之中',
    icon: '🧊',
    color: 0x4fc3f7,
    bodyColor: 0x81d4fa,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 3, attackBonus: 5, speedBonus: 4, defenseBonus: 5 },
    passive: { type: 'ice_body', value: 0.15, description: '15% 概率免疫伤害，被攻击时冻结攻击者' },
    active: { name: '绝对零度', cooldown: 16000, duration: 4000, type: 'absolute_zero', value: 1, description: '全屏敌人冻结 4 秒' },
    active2: { name: '绝对零度·改', cooldown: 13000, duration: 4000, type: 'absolute_zero_2', value: 1, description: '绝对零度的快速版本' },
    ultimate: { name: '冰封永恒', cooldown: 60000, duration: 0, type: 'eternal_frost', value: 10, description: '释放永恒寒冰，全屏伤害 10 并冻结 5 秒' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        暗系 (6只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_bat',
    name: '小蝙蝠',
    element: 'dark',
    rarity: 'common',
    description: '在黑暗中无声飞行的夜行生物',
    icon: '🦇',
    color: 0x616161,
    bodyColor: 0x757575,
    eyeColor: 0xe53935,
    stats: { hpBonus: 0, attackBonus: 1, speedBonus: 3, defenseBonus: 0 },
    passive: { type: 'night_vision', value: 1, description: '在黑暗关卡视野不减少' },
    active: { name: '超音波', cooldown: 10000, duration: 3000, type: 'supersonic', value: 1, description: '释放超音波，3秒内眩晕附近敌人' },
    active2: { name: '超音波·改', cooldown: 7000, duration: 3000, type: 'supersonic_2', value: 1, description: '超音波的快速版本' },
    ultimate: { name: '吸血之翼', cooldown: 30000, duration: 0, type: 'leech_life', value: 3, description: '吸取敌人生命，伤害 3 并回复自身 3 条命' },
  },
  {
    id: 'pet_ghost',
    name: '幽灵仔',
    element: 'dark',
    rarity: 'uncommon',
    description: '漂浮的紫色幽灵，喜欢恶作剧',
    icon: '👻',
    color: 0x7b1fa2,
    bodyColor: 0x9c27b0,
    eyeColor: 0xffffff,
    stats: { hpBonus: 1, attackBonus: 2, speedBonus: 2, defenseBonus: 0 },
    passive: { type: 'phase_through', value: 0.10, description: '10% 概率穿过敌人而不受伤害' },
    active: { name: '暗影潜行', cooldown: 14000, duration: 3000, type: 'shadow_sneak', value: 3, description: '3秒内隐身，攻击时现身造成 3 点伤害' },
    active2: { name: '暗影潜行·改', cooldown: 11000, duration: 3000, type: 'shadow_sneak_2', value: 2, description: '暗影潜行的快速版本' },
    ultimate: { name: '噩梦', cooldown: 38000, duration: 5000, type: 'nightmare', value: 2, description: '5秒内所有敌人持续掉血且无法攻击' },
  },
  {
    id: 'pet_murkrow',
    name: '黑暗鸦',
    element: 'dark',
    rarity: 'uncommon',
    description: '被视为不祥之兆的暗夜乌鸦',
    icon: '🐦‍⬛',
    color: 0x37474f,
    bodyColor: 0x455a64,
    eyeColor: 0xffd600,
    stats: { hpBonus: 0, attackBonus: 3, speedBonus: 3, defenseBonus: 0 },
    passive: { type: 'crit_boost', value: 0.10, description: '暴击率 +10%' },
    active: { name: '暗袭', cooldown: 10000, duration: 0, type: 'sucker_punch', value: 4, description: '先制攻击，必定暴击伤害 4' },
    active2: { name: '暗袭·改', cooldown: 7000, duration: 0, type: 'sucker_punch_2', value: 3, description: '暗袭的快速版本' },
    ultimate: { name: '暗夜爆风', cooldown: 38000, duration: 0, type: 'dark_pulse', value: 6, description: '释放暗之波动，全屏伤害 6 点' },
    evolution: { toPetId: 'pet_honchkrow', requiredLevel: 6, requiredShards: 40 },
  },
  {
    id: 'pet_umbreon',
    name: '月伊布',
    element: 'dark',
    rarity: 'epic',
    description: '月光下进化的暗夜精灵，环纹发光',
    icon: '🌙',
    color: 0x212121,
    bodyColor: 0x303030,
    eyeColor: 0xffd600,
    stats: { hpBonus: 3, attackBonus: 3, speedBonus: 2, defenseBonus: 5 },
    passive: { type: 'moonlight', value: 1, description: '每 12 秒恢复 1 条生命' },
    active: { name: '月光冲击', cooldown: 14000, duration: 0, type: 'moonlight_blast', value: 5, description: '聚集月光释放，伤害 5 点' },
    active2: { name: '月光冲击·改', cooldown: 11000, duration: 0, type: 'moonlight_blast_2', value: 4, description: '月光冲击的快速版本' },
    ultimate: { name: '暗夜领域', cooldown: 42000, duration: 6000, type: 'dark_domain', value: 2, description: '6秒内全屏减速，自身攻击力翻倍' },
  },
  {
    id: 'pet_darkrai',
    name: '达克莱伊',
    element: 'dark',
    rarity: 'legendary',
    description: '带来噩梦的暗黑精灵',
    icon: '🌑',
    color: 0x1a1a2e,
    bodyColor: 0x212121,
    eyeColor: 0xc62828,
    stats: { hpBonus: 2, attackBonus: 6, speedBonus: 5, defenseBonus: 2 },
    passive: { type: 'bad_dreams', value: 1, description: '敌人每秒自动掉血 1 点' },
    active: { name: '暗黑洞', cooldown: 16000, duration: 5000, type: 'dark_void', value: 1, description: '释放黑暗空间，全屏敌人沉睡 5 秒' },
    active2: { name: '暗黑洞·改', cooldown: 13000, duration: 5000, type: 'dark_void_2', value: 1, description: '暗黑洞的快速版本' },
    ultimate: { name: '噩梦侵蚀', cooldown: 60000, duration: 8000, type: 'nightmare侵蚀', value: 3, description: '8秒内敌人持续掉血且无法行动' },
  },
  {
    id: 'pet_spiritomb',
    name: '花岩怪',
    element: 'dark',
    rarity: 'epic',
    description: '由 108 个灵魂融合而成的怨念集合体',
    icon: '😈',
    color: 0x4a148c,
    bodyColor: 0x6a1b9a,
    eyeColor: 0x76ff03,
    stats: { hpBonus: 2, attackBonus: 4, speedBonus: 0, defenseBonus: 5 },
    passive: { type: 'curse', value: 1, description: '被攻击时反弹 1 点伤害给攻击者' },
    active: { name: '怨念', cooldown: 14000, duration: 0, type: 'grudge', value: 5, description: '释放怨念，伤害 5 点并降低敌人防御' },
    active2: { name: '怨念·改', cooldown: 11000, duration: 0, type: 'grudge_2', value: 4, description: '怨念的快速版本' },
    ultimate: { name: '封印', cooldown: 45000, duration: 6000, type: 'sealed', value: 1, description: '封印全屏敌人 6 秒，期间敌人无法行动' },
  },

  // ═══════════════════════════════════════════════════════════════
  //                        光系 (6只)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pet_pixie',
    name: '小精灵',
    element: 'light',
    rarity: 'common',
    description: '闪烁光芒的微小精灵，善良温柔',
    icon: '✨',
    color: 0xffd700,
    bodyColor: 0xffe082,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 1, attackBonus: 0, speedBonus: 1, defenseBonus: 1 },
    passive: { type: 'heal_boost', value: 0.10, description: '回复效果 +10%' },
    active: { name: '治愈之光', cooldown: 12000, duration: 0, type: 'heal_pulse', value: 2, description: '回复 2 条生命' },
    active2: { name: '治愈之光·改', cooldown: 9000, duration: 0, type: 'heal_pulse_2', value: 1, description: '治愈之光的快速版本' },
    ultimate: { name: '光之祝福', cooldown: 35000, duration: 5000, type: 'blessing', value: 1, description: '5秒内持续回复生命，受到伤害减半' },
  },
  {
    id: 'pet_clefairy',
    name: '皮皮',
    element: 'light',
    rarity: 'uncommon',
    description: '来自月球的妖精，歌声优美',
    icon: '🧚',
    color: 0xf8bbd0,
    bodyColor: 0xfce4ec,
    eyeColor: 0x1a1a2e,
    stats: { hpBonus: 2, attackBonus: 1, speedBonus: 1, defenseBonus: 2 },
    passive: { type: 'friend_guard', value: 0.05, description: '全队受到伤害 -5%' },
    active: { name: '月光', cooldown: 14000, duration: 0, type: 'moonlight_2', value: 3, description: '回复 3 条生命' },
    active2: { name: '月光·改', cooldown: 11000, duration: 0, type: 'moonlight_2_2', value: 2, description: '月光的快速版本' },
    ultimate: { name: '宇宙力量', cooldown: 40000, duration: 6000, type: 'cosmic_power', value: 1, description: '6秒内全属性提升 30%' },
  },
  {
    id: 'pet_ralts',
    name: '拉鲁拉丝',
    element: 'light',
    rarity: 'uncommon',
    description: '能感知人心的超能力精灵',
    icon: '🧚',
    color: 0xe8f5e9,
    bodyColor: 0xc8e6c9,
    eyeColor: 0xc62828,
    stats: { hpBonus: 1, attackBonus: 2, speedBonus: 2, defenseBonus: 1 },
    passive: { type: 'empathy', value: 1, description: '感知敌人攻击，闪避率 +8%' },
    active: { name: '念力', cooldown: 12000, duration: 3000, type: 'psychic_2', value: 3, description: '释放念力，3秒内减速敌人 50%' },
    active2: { name: '念力·改', cooldown: 9000, duration: 3000, type: 'psychic_2_2', value: 2, description: '念力的快速版本' },
    ultimate: { name: '预知未来', cooldown: 38000, duration: 0, type: 'future_sight', value: 6, description: '2秒后对全屏敌人造成 6 点伤害' },
    evolution: { toPetId: 'pet_gardevoir', requiredLevel: 6, requiredShards: 40 },
  },
  {
    id: 'pet_gardevoir',
    name: '沙奈朵',
    element: 'light',
    rarity: 'rare',
    description: '能预见未来的超能精灵，守护主人不惜牺牲',
    icon: '👗',
    color: 0xe8f5e9,
    bodyColor: 0xc8e6c9,
    eyeColor: 0xc62828,
    stats: { hpBonus: 2, attackBonus: 4, speedBonus: 3, defenseBonus: 2 },
    passive: { type: 'synchronize', value: 1, description: '被施加负面状态时反弹给攻击者' },
    active: { name: '治愈波动', cooldown: 14000, duration: 0, type: 'healing_wave', value: 4, description: '回复 4 条生命并清除负面状态' },
    active2: { name: '治愈波动·改', cooldown: 11000, duration: 0, type: 'healing_wave_2', value: 3, description: '治愈波动的快速版本' },
    ultimate: { name: '月亮之力', cooldown: 42000, duration: 0, type: 'moonblast', value: 8, description: '释放月之力，全屏伤害 8 点' },
    evolution: { toPetId: 'pet_gallade', requiredLevel: 8, requiredShards: 60 },
  },
  {
    id: 'pet_espeon',
    name: '太阳伊布',
    element: 'light',
    rarity: 'epic',
    description: '阳光下进化的超能精灵，预知能力极强',
    icon: '☀️',
    color: 0xf57c00,
    bodyColor: 0xff9800,
    eyeColor: 0x7b1fa2,
    stats: { hpBonus: 1, attackBonus: 5, speedBonus: 4, defenseBonus: 2 },
    passive: { type: 'sun_power', value: 0.10, description: '攻击力 +10%，每 10 秒恢复 1 条命' },
    active: { name: '精神强念', cooldown: 14000, duration: 0, type: 'psychic_3', value: 6, description: '释放精神冲击，伤害 6 点' },
    active2: { name: '精神强念·改', cooldown: 11000, duration: 0, type: 'psychic_3_2', value: 5, description: '精神强念的快速版本' },
    ultimate: { name: '晨光', cooldown: 42000, duration: 0, type: 'morning_sun', value: 6, description: '回复 6 条生命并获得 5 秒无敌' },
  },
  {
    id: 'pet_arceus',
    name: '阿尔宙斯',
    element: 'light',
    rarity: 'legendary',
    description: '创造世界的传说宝可梦，全能之神',
    icon: '👑',
    color: 0xffd700,
    bodyColor: 0xffe082,
    eyeColor: 0xc62828,
    stats: { hpBonus: 5, attackBonus: 6, speedBonus: 5, defenseBonus: 5 },
    passive: { type: 'multitype', value: 0.10, description: '全属性 +10%，免疫一次致命伤害' },
    active: { name: '制裁光砾', cooldown: 16000, duration: 0, type: 'judgment', value: 8, description: '释放神之制裁，全屏伤害 8 点' },
    active2: { name: '制裁光砾·改', cooldown: 13000, duration: 0, type: 'judgment_2', value: 7, description: '制裁光砾的快速版本' },
    ultimate: { name: '创世之光', cooldown: 60000, duration: 10000, type: 'creation', value: 1, description: '10秒内全属性翻倍，攻击附带光属性伤害' },
  },
];

export const PET_EXP_PER_LEVEL = [0, 10, 25, 50, 80, 120, 170, 230, 300, 400];
export const MAX_PET_LEVEL = 10;
export const MAX_OWNED_PETS = 6;

export function getPetById(id: string): PetDef | undefined {
  return PETS.find(p => p.id === id);
}

export function getPetsByElement(element: PetElement): PetDef[] {
  return PETS.filter(p => p.element === element);
}

export function getPetsByRarity(rarity: PetRarity): PetDef[] {
  return PETS.filter(p => p.rarity === rarity);
}
