server {
    listen 80;
    server_name localhost;

    location /jump-game/ {
        alias /usr/share/nginx/html/jump-game/;
        try_files $uri $uri/ /jump-game/index.html;
    }

    location / {
        return 301 /jump-game/;
    }
}
